# Generated by Django 4.1.3 on 2023-01-05 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='beer',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='beers.beer'),
        ),
    ]
