# Generated by Django 4.1.3 on 2023-01-05 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_alter_beer_name_alter_review_beer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beers.beer'),
        ),
    ]
